### ISSUE TITLE
License Question - Static Linking Exception?

### ISSUE THREAD

**Issue by bitbanger86** [mguentner/cannelloni_ports#1]
Hi there.

I noticed that you chose LGPLv3 as the license for this LWIP based embedded port of 
cannelloni, as opposed to GPLv3 for the Linux version.

So it appears there is an intent to allow this embedded cannelloni port library to be integrated with non-gpl application code.  However, in practice, I don't think that is viable right now in many cases unless this repository is changed to LGPLv3 /w static linking exception or MPLv2.

I've included info on the issues with LGPL static linking here:
- https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)
- https://www.gnu.org/licenses/gpl-faq.en.html#LGPLStaticVsDynamic

The majority of embedded code, such as a Infineon Aurix TC275, typically has all the code statically linked together, and deployed using a HEX file.  So it doesn't seem like LGPL is the best fit for this scenario.

My understanding is Mozilla Public License v2 is essentially LGPL+sle exception.  So legally that is much clearer and easier to comply with.
- https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)
 
> MPL is a copyleft license that is easy to comply with. You must make the source code for any of your changes available under MPL, but you can combine the MPL software with proprietary code, as long as you keep the MPL code in separate files. Version 2.0 is, by default, compatible with LGPL and GPL version 2 or greater. You can distribute binaries under a proprietary license, as long as you make the source available under MPL.

Anyways, cool project.  I'm curious what your intent with the license is, and if you would consider changing it.

Thanks.

**Comment by mguentner** [comment]
My intent to keep the core implementation as free as possible but I know that especially on embedded platforms, like Aurix, single static image are quite common and the vendors are mostly using unfree licenses for their own source code. That's why I used the LGPLv3 when I published the lwip port.

But your point seems valid. I did not think it through how LGPLv3 works in binary system images.
Thank you for the input!
I will have a look at the MPL in the next days and will think about a relicensing / double licensing.

I am curious: Are you considering integrating it into a product?

**Comment by bitbanger86** [comment]
I have been investigating bridging CAN and Ethernet UDP traffic for an R&D automotive device and came across this project and related whitepaper.  I have been considering using the Cannelloni protocol to leverage the existing tools and participate with the open development should I make changes / improvements.
  
Reading the licensing for the embedded port however made it seem I may have legal issues if I want to integrate LGPLv3 code with my embedded device firmware.    
Preferably if the licensing changed, the opensource / free components can remain free, while the non Cannelloni related components can be licensed independently.

Thanks for the consideration.

**Comment by mguentner** [comment]
Sorry for the long delay.
I have thought a lot about this and decided not to re license under MPL.
While I understand your reasons and the environment you are working in, I don't want to loosen the license because of commercial reasons.

I consider the protocol description you can find here https://github.com/mguentner/cannelloni/blob/master/doc/udp_format.md CC-BY-SA, you can use it to implement your own parser and bridge. Given the complexity of the protocol this should not take long. If you ever happen to publish your implementation or more parts of your R/D device, feel free to file PR against the cannelloni or cannelloni_ports repository.
